### ISSUE TITLE
UDP Support

### ISSUE THREAD

**Issue by rezadindar** [Gowee/noisy-shuttle#2]
This project is really great but It seems that the project does not support UDP (udp over tcp). Do you have any plans to add it?

**Comment by Gowee** [comment]
The project is separated into https://github.com/Gowee/noisy-shuttle/tree/main/tunnel (core protocol for camouflaging as TLS) and https://github.com/Gowee/noisy-shuttle/tree/main/shuttle (Trojan-like proxy over the core protocol).  The latter does handle Socks5 UDP ASSOCIATE. 

Check:
https://github.com/Gowee/noisy-shuttle/blob/9be385715c7f399ef60c989b3bd59cc848d0fff1/shuttle/src/client/plain.rs#L105
https://github.com/Gowee/noisy-shuttle/blob/9be385715c7f399ef60c989b3bd59cc848d0fff1/shuttle/src/server.rs#L83
